# Numpy

## Task 1

You should import the necessary libraries. You will use `numpy` and `sys` libraries.


> Don't forget to import `numpy` in the short form.

In [2]:
import sys
import numpy as np

## Task 2

Create arrays with using Python default syntax and using `numpy`. Also, print the size of the arrays in bytes. You should use `sys` library for this task.

Requirements for arrays:
* length of the array should be `1000`;
* array should contain zeros;
* the second array should be generated by `numpy` library, and should have as little memory as possible.

In [7]:
lst = [i for i in range(1000)]
sys.getsizeof(lst)

8856

In [6]:
arr = np.array([i for i in range(1000)])
sys.getsizeof(arr)

8112

## Task 3

Write manually a small float array using `numpy` syntax number should be in the range from `0` to `10.0`. Also, you should get the first, the third, and the last elements of the array using multi-indexing.

Requirements:
* length of the array should be from `5` to `10`.

In [22]:
arr = np.array([i for i in range(10)], dtype="f")
arr[[0, 2, -1]]

array([0., 2., 9.], dtype=float32)

## Task 4

You have the array `array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])` using multi-indexing you should summarize a subsequence of an array and get the `27` as the result.

In [32]:
array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])
elements = array[[0, 1, 4, 7]]
np.sum(elements)

np.float64(27.0)

## Task 5

You have a matrix `A`:

```python
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])
```

Follow the comments in the next cells and write the code.

In [21]:
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])

### Task 5.1 Find the mean for each column by `x` axis

In [33]:
A.mean(axis=0)

array([2. , 8.4])

### Task 5.2 Get the standard deviation by `y` axis

In [35]:
A.std(axis=1)

array([2.5, 3. , 4. , 3.5, 3. ])

### Task 5.3 Get the sum of all elements in `A` by `y` axis

In [36]:
np.sum(A, axis=0)

array([10, 42])

### Task 5.4 Get the following result using multi-dim selection:

```python
[
    [1, 6],
    [2, 8],
 ]
```

In [37]:
A[:2]

array([[1, 6],
       [2, 8]])

##  Task 5.5. Get the following result using multi-dim selection:
```python
[
    [1, 6],
    [3, 11],
    [1, 7]
 ]
```

In [38]:
A[[0, len(A) // 2, -1]]

array([[ 1,  6],
       [ 3, 11],
       [ 1,  7]])

## Task 6

Rewrite Python code to `numpy` code. Also, estimate the time of execution for both implementations.

> Please, note: `unknown_signature` this name just hide the real name of the function, to make the task more complicated.

### Task 6.1

In [60]:
# Python code
[i for i in range(1000000)]


Execution time: 0.03521657 seconds


In [78]:
import time

start = time.perf_counter()
numpy = np.arange(1000000)
end = time.perf_counter()
elapsed = end - start

print(f"\nExecution time: {elapsed:.16f} seconds")


Execution time: 0.0023078918457031 seconds


### Task 6.2

In [67]:
# Python code
def unknown_signature(vector1, vector2):
    result = 0
    for i in range(len(vector1)):
        result += vector1[i] * vector2[i]
    return result

vector1 = [1, 2, 3]
vector2 = [4, 5, 6]
result = 0

%time unknown_signature(vector1, vector2)
result

CPU times: total: 0 ns
Wall time: 0 ns


0

In [79]:
import time
import numpy as np

def unknown_signature_numpy(vector_num_1, vector_num_2):
    return np.dot(vector_num_1, vector_num_2)

vector_num_1 = np.array([1, 2, 3])
vector_num_2 = np.array([4, 5, 6])

start = time.perf_counter()
result_num = unknown_signature_numpy(vector_num_1, vector_num_2)
end = time.perf_counter()
elapsed = end - start

print(f"Execution time: {elapsed:.16f} seconds")
print(f"Result: {result_num}")

Execution time: 0.0000000000000000 seconds
Result: 32


### Task 6.3

In [26]:
# Python code
def unknown_signature(matrix1, matrix2):
    result = []
    for i in range(len(matrix1)):
        row = []
        for j in range(len(matrix1[i])):
            row.append(matrix1[i][j] * matrix2[i][j])
        result.append(row)
    return result

matrix1 = [[1, 2], [3, 4]]
matrix2 = [[5, 6], [7, 8]]

In [93]:
def unknown_signature_numpy(num_matrix1, num_matrix2):
    num_matrix1 = np.array(num_matrix1)
    num_matrix2 = np.array(num_matrix2)
    
    num_result = num_matrix1 * num_matrix2
    
    return num_result

num_matrix1 = [[1, 2], [3, 4]]
num_matrix2 = [[5, 6], [7, 8]]

start = time.perf_counter()
num_result = unknown_signature_numpy(num_matrix1, num_matrix2)
end = time.perf_counter()
elapsed = end - start

print(f"Execution time: {elapsed:.16f} seconds")
print(f"Result:\n{num_result}")

Execution time: 0.0000467000008939 seconds
Result:
[[ 5 12]
 [21 32]]


### Task 6.4

In [ ]:
# Python code
def unknown_signature(lst):
    total = 0
    for num in lst:
        total += num
    result = total / len(lst)
    return result

lst = [1, 2, 3, 4, 5]

In [91]:
def unknown_signature_numpy(lst_numpy):
    total_numpy = np.sum(lst_numpy)
    result_numpy = total_numpy / len(lst_numpy)
    return result_numpy

lst_numpy = [1, 2, 3, 4, 5]

start = time.perf_counter()
num_result = unknown_signature_numpy(lst_numpy)
end = time.perf_counter()
elapsed = end - start

print(f"Execution time: {elapsed:.16f} seconds")
print(f"Result:\n{num_result}")

Execution time: 0.0000000000000000 seconds
Result:
3.0


## Task 7

Rewrite Python code to `numpy` code (Masks).

### Task 7.1

In [84]:
# Python code
def unknown_signature(lst, mask, new_value):
    for i in range(len(lst)):
        if mask[i]:
            lst[i] = new_value

lst = [1, 2, 3, 4, 5]
mask = [True, False, True, False, True]
new_value = 0
unknown_signature(lst, mask, new_value)
lst

Execution time: 0.0000000000000000 seconds
Result:
[[ 5 12]
 [21 32]]


In [94]:
def unknown_signature_numpy(lst_numpy, mask_numpy, new_value_numpy):
    lst_numpy[mask_numpy] = new_value_numpy

lst_numpy = np.array([1, 2, 3, 4, 5])
mask_numpy = np.array([True, False, True, False, True])
new_value_numpy = 0

start = time.perf_counter()
unknown_signature_numpy(lst_numpy, mask_numpy, new_value_numpy)
end = time.perf_counter()
elapsed = end - start

lst_numpy
print(f"Execution time: {elapsed:.16f} seconds")
print(f"Result:\n{num_result}")

Execution time: 0.0000347999994119 seconds
Result:
[[ 5 12]
 [21 32]]


### Task 7.2

In [33]:
# Python code
def unknown_signature(lst1, lst2):
    bitwise_complement = [~x for x in lst1]
    bitwise_and = [x & y for x, y in zip(lst1, lst2)]
    bitwise_or = [x | y for x, y in zip(lst1, lst2)]
    return bitwise_complement, bitwise_and, bitwise_or

list1 = [5, 2, 7, 4, 9]
list2 = [3, 6, 1, 8, 10]
result_bitwise_complement, result_bitwise_and, result_bitwise_or = unknown_signature(list1, list2)
result_bitwise_complement, result_bitwise_and, result_bitwise_or

In [96]:
def unknown_signature_numpy(lst1_numpy, lst2_numpy):
    lst1_numpy_res = np.array(lst1_numpy)
    lst2_numpy_res = np.array(lst2_numpy)
    
    bitwise_complement_numpy = np.bitwise_not(lst1_numpy_res)
    bitwise_and_numpy = np.bitwise_and(lst1_numpy_res, lst2_numpy_res)
    bitwise_or_numpy = np.bitwise_or(lst1_numpy_res, lst2_numpy_res)
    
    return bitwise_complement_numpy, bitwise_and_numpy, bitwise_or_numpy

lst1_numpy = [5, 2, 7, 4, 9]
lst2_numpy = [3, 6, 1, 8, 10]

start = time.perf_counter()
result_bitwise_complement_numpy, result_bitwise_and_numpy, result_bitwise_or_numpy = unknown_signature_numpy(lst1_numpy, lst2_numpy)
result_bitwise_complement_numpy, result_bitwise_and_numpy, result_bitwise_or_numpy

end = time.perf_counter()
elapsed = end - start

print(f"Execution time: {elapsed:.16f} seconds")
print(f"Result:\n{num_result}")

Execution time: 0.0000673000013194 seconds
Result:
[[ 5 12]
 [21 32]]


### Task 7.3 Optional

In [34]:
# Python code
def unknown_signature(lst):
    result = []
    for num in lst:
        if num % 2 == 0 and (num % 3 == 0 or num > 10):
            modified_num = (num ^ 7) + 2
            result.append(modified_num)
    return result

my_list = [6, 9, 12, 14, 17, 20]
result_python_style = unknown_signature(my_list)
result_python_style

[3, 13, 11, 21]

In [98]:
def unknown_signature_numpy(lst_np):
    # Change Python list to NumPy array
    lst_arr = np.array(lst_np)
    
    # Condition for filter values
    condition = (lst_arr % 2 == 0) & ((lst_arr % 3 == 0) | (lst_arr > 10))
    
    # Set modified values
    modified_nums = (lst_arr[condition] ^ 7) + 2
    
    return modified_nums

my_list_np = [6, 9, 12, 14, 17, 20]

start = time.perf_counter()
result_numpy_style = unknown_signature_numpy(my_list_np)
result_numpy_style

end = time.perf_counter()
elapsed = end - start

print(f"Execution time: {elapsed:.16f} seconds")
print(f"Result:\n{num_result}")

Execution time: 0.0001222999999300 seconds
Result:
[[ 5 12]
 [21 32]]
